version: '3'
services:
  front:
    container_name: front
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: yarn dev

volumes:
  node_modules: